### ISSUE TITLE
No results.xlsx file being generated

### ISSUE THREAD

**Issue by calume** [bukhsh/oats#51]
On the python package, when running 
import oats
oats.dcopf()

There is no results.xlsx file created in the working directory.

**Comment by calume** [comment]
Understood, results.xlsx file is only generated for a local solver,
Default should not be NEOS if it does not generate a results.xlsx file which you state in the readthedocs will be generated

Also in results.xlsx (when generated from local solver), within generator you have PG(MW) which is blank and pG(MW), need some explanation for what these things are.

Look at ordering of demands in results.xlsx. out of order. Same for all other tabs (gens etc).

**Comment by bukhsh** [comment]
the issue is resolved...I'll add a issue for a script that can produce a results.xlsx file from NEOS output.
